services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
#      - ./db/:/docker-entrypoint-initdb.d/
    env_file:
      - env/db.env

  server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  data: