server:
  port: 8080
  address:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/bare-ground
    username: cmjcm
    password: 1423
  jpa:
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: update

# swagger
springdoc:
  swagger-ui:
    path: swagger-ui
