server:
  port: 8080
  address:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: update

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


# swagger
springdoc:
  swagger-ui:
    path: swagger-ui
